name: Build
on:
  push:
    branches-ignore:
      - build
  workflow_dispatch:
jobs:
  buildLnx:
    name: Debian, RedHat Package(.deb, .rpm)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          persist-credentials: false 
      - name: Install Dependencies
        run: yarn
      - name: Install rpm, fakeroot, and dpkg
        run: |
          sudo apt update -y
          sudo apt install -y rpm fakeroot dpkg
      - name: Build
        run: yarn build:lnx
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lnx
          path: |
            out/youtube-downloader_*.*.*_amd64.deb
            out/youtube-downloader-*.*.*.x86_64.rpm
  buildMac:
    name: macOS Application(.dmg)
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          persist-credentials: false 
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build:mac
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mac
          path: out/YouTube Downloader-*.*.*.dmg
  buildWin:
    name: Windows Executable and Installer(.exe, .msi)
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          persist-credentials: false 
      - name: Install Dependencies
        run: yarn
      - name: Add light and candle to PATH
        run: echo "C:\Program Files (x86)\Wix Toolset v3.11\bin" >> $GITHUB_PATH
        shell: bash
      - name: Build
        run: |
          yarn build:win
          node msi.js
        shell: bash
      - name: Upload Squirrel Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: squirrel
          path: out/squirrel-windows
      - name: Upload MSI Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: msi
          path: out/msi
  publish:
    name: Publish
    needs: [buildLnx, buildWin, buildMac]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Determine tag name
        id: tagname
        run: echo "::set-output name=name::$(node -e "console.log(require('./package.json').version)")"
      - name: Create a new Tag
        run: git tag v${{ steps.tagname.outputs.name }}
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: "변경사항: \n\n**다운로드/설치 전에 꼭 [여기](https://github.com/team-int/youtube-downloader/blob/main/installation.md)를 읽어주세요!**"
          draft: true
          tag_name: ${{ steps.tagname.outputs.name }}
          files: |
            lnx/*
            mac/*
            squirrel/*
            msi/*
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}